/**
 * Schema helpers for Drizzle ORM
 *
 * These helpers create the necessary tables for @sylphx/lingua.
 * Import and use in your Drizzle schema file.
 *
 * @example PostgreSQL
 * ```ts
 * // schema.ts
 * import { pgTable, text, timestamp, integer, boolean, unique } from 'drizzle-orm/pg-core';
 * import { createLinguaSchema } from '@sylphx/lingua-drizzle/schema';
 *
 * export const { linguaSources, linguaTranslations } = createLinguaSchema({
 *   pgTable,
 *   text,
 *   timestamp,
 *   integer,
 *   boolean,
 *   unique,
 * });
 * ```
 *
 * @example SQLite
 * ```ts
 * // schema.ts
 * import { sqliteTable, text, integer } from 'drizzle-orm/sqlite-core';
 * import { createLinguaSchemaSQLite } from '@sylphx/lingua-drizzle/schema';
 *
 * export const { linguaSources, linguaTranslations } = createLinguaSchemaSQLite({
 *   sqliteTable,
 *   text,
 *   integer,
 * });
 * ```
 */

// ============================================
// PostgreSQL Schema
// ============================================

export interface PostgresSchemaHelpers {
	pgTable: typeof import('drizzle-orm/pg-core').pgTable;
	text: typeof import('drizzle-orm/pg-core').text;
	timestamp: typeof import('drizzle-orm/pg-core').timestamp;
	integer: typeof import('drizzle-orm/pg-core').integer;
	boolean: typeof import('drizzle-orm/pg-core').boolean;
	unique: typeof import('drizzle-orm/pg-core').unique;
	serial?: typeof import('drizzle-orm/pg-core').serial;
}

export interface LinguaSchemaOptions {
	/**
	 * Custom table name for sources (default: 'lingua_sources')
	 */
	sourcesTable?: string;
	/**
	 * Custom table name for translations (default: 'lingua_translations')
	 */
	translationsTable?: string;
}

/**
 * Create Lingua schema for PostgreSQL
 */
export function createLinguaSchema<T extends PostgresSchemaHelpers>(
	helpers: T,
	options: LinguaSchemaOptions = {}
) {
	const { pgTable, text, timestamp, integer, boolean, unique, serial } = helpers;
	const sourcesTableName = options.sourcesTable ?? 'lingua_sources';
	const translationsTableName = options.translationsTable ?? 'lingua_translations';

	const linguaSources = pgTable(sourcesTableName, {
		id: serial ? serial('id').primaryKey() : integer('id').primaryKey().generatedAlwaysAsIdentity(),
		hash: text('hash').notNull().unique(),
		text: text('text').notNull(),
		context: text('context'),
		occurrences: integer('occurrences').default(1).notNull(),
		firstSeenAt: timestamp('first_seen_at', { withTimezone: true }).defaultNow().notNull(),
		lastSeenAt: timestamp('last_seen_at', { withTimezone: true }).defaultNow().notNull(),
	});

	const linguaTranslations = pgTable(
		translationsTableName,
		{
			id: serial ? serial('id').primaryKey() : integer('id').primaryKey().generatedAlwaysAsIdentity(),
			locale: text('locale').notNull(),
			hash: text('hash').notNull(),
			text: text('text').notNull(),
			autoGenerated: boolean('auto_generated').default(false).notNull(),
			reviewed: boolean('reviewed').default(false).notNull(),
			createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
			updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
		},
		(table) => [unique().on(table.locale, table.hash)]
	);

	return { linguaSources, linguaTranslations };
}

// ============================================
// SQLite Schema
// ============================================

export interface SQLiteSchemaHelpers {
	sqliteTable: typeof import('drizzle-orm/sqlite-core').sqliteTable;
	text: typeof import('drizzle-orm/sqlite-core').text;
	integer: typeof import('drizzle-orm/sqlite-core').integer;
	unique?: typeof import('drizzle-orm/sqlite-core').unique;
}

/**
 * Create Lingua schema for SQLite
 */
export function createLinguaSchemaSQLite<T extends SQLiteSchemaHelpers>(
	helpers: T,
	options: LinguaSchemaOptions = {}
) {
	const { sqliteTable, text, integer, unique } = helpers;
	const sourcesTableName = options.sourcesTable ?? 'lingua_sources';
	const translationsTableName = options.translationsTable ?? 'lingua_translations';

	const linguaSources = sqliteTable(sourcesTableName, {
		id: integer('id').primaryKey({ autoIncrement: true }),
		hash: text('hash').notNull().unique(),
		text: text('text').notNull(),
		context: text('context'),
		occurrences: integer('occurrences').default(1).notNull(),
		firstSeenAt: integer('first_seen_at', { mode: 'timestamp' })
			.$defaultFn(() => new Date())
			.notNull(),
		lastSeenAt: integer('last_seen_at', { mode: 'timestamp' })
			.$defaultFn(() => new Date())
			.notNull(),
	});

	const linguaTranslations = sqliteTable(
		translationsTableName,
		{
			id: integer('id').primaryKey({ autoIncrement: true }),
			locale: text('locale').notNull(),
			hash: text('hash').notNull(),
			text: text('text').notNull(),
			autoGenerated: integer('auto_generated', { mode: 'boolean' }).default(false).notNull(),
			reviewed: integer('reviewed', { mode: 'boolean' }).default(false).notNull(),
			createdAt: integer('created_at', { mode: 'timestamp' })
				.$defaultFn(() => new Date())
				.notNull(),
			updatedAt: integer('updated_at', { mode: 'timestamp' })
				.$defaultFn(() => new Date())
				.notNull(),
		},
		(table) => (unique ? [unique().on(table.locale, table.hash)] : [])
	);

	return { linguaSources, linguaTranslations };
}

// ============================================
// MySQL Schema
// ============================================

export interface MySQLSchemaHelpers {
	mysqlTable: typeof import('drizzle-orm/mysql-core').mysqlTable;
	text: typeof import('drizzle-orm/mysql-core').text;
	varchar: typeof import('drizzle-orm/mysql-core').varchar;
	timestamp: typeof import('drizzle-orm/mysql-core').timestamp;
	int: typeof import('drizzle-orm/mysql-core').int;
	boolean: typeof import('drizzle-orm/mysql-core').boolean;
	unique?: typeof import('drizzle-orm/mysql-core').unique;
	serial?: typeof import('drizzle-orm/mysql-core').serial;
}

/**
 * Create Lingua schema for MySQL
 */
export function createLinguaSchemaMySQL<T extends MySQLSchemaHelpers>(
	helpers: T,
	options: LinguaSchemaOptions = {}
) {
	const { mysqlTable, text, varchar, timestamp, int, boolean, unique, serial } = helpers;
	const sourcesTableName = options.sourcesTable ?? 'lingua_sources';
	const translationsTableName = options.translationsTable ?? 'lingua_translations';

	const linguaSources = mysqlTable(sourcesTableName, {
		id: serial ? serial('id').primaryKey() : int('id').primaryKey().autoincrement(),
		hash: varchar('hash', { length: 32 }).notNull().unique(),
		text: text('text').notNull(),
		context: varchar('context', { length: 255 }),
		occurrences: int('occurrences').default(1).notNull(),
		firstSeenAt: timestamp('first_seen_at').defaultNow().notNull(),
		lastSeenAt: timestamp('last_seen_at').defaultNow().notNull(),
	});

	const linguaTranslations = mysqlTable(
		translationsTableName,
		{
			id: serial ? serial('id').primaryKey() : int('id').primaryKey().autoincrement(),
			locale: varchar('locale', { length: 10 }).notNull(),
			hash: varchar('hash', { length: 32 }).notNull(),
			text: text('text').notNull(),
			autoGenerated: boolean('auto_generated').default(false).notNull(),
			reviewed: boolean('reviewed').default(false).notNull(),
			createdAt: timestamp('created_at').defaultNow().notNull(),
			updatedAt: timestamp('updated_at').defaultNow().notNull(),
		},
		(table) => (unique ? [unique().on(table.locale, table.hash)] : [])
	);

	return { linguaSources, linguaTranslations };
}

// ============================================
// Type Inference Helpers
// ============================================

/**
 * Infer the type of a Lingua sources table
 */
export type LinguaSourcesTable = ReturnType<typeof createLinguaSchema>['linguaSources'];

/**
 * Infer the type of a Lingua translations table
 */
export type LinguaTranslationsTable = ReturnType<typeof createLinguaSchema>['linguaTranslations'];
