/**
 * tRPC router for translation admin
 *
 * @example
 * ```ts
 * // server/trpc/routers/admin.ts
 * import { createAdminRouter } from '@sylphx/rosetta-admin/server/trpc';
 * import { createAiSdkTranslator } from '@sylphx/rosetta-translator-ai-sdk';
 * import { createOpenRouter } from '@openrouter/ai-sdk-provider';
 * import { storage } from '@/lib/rosetta';
 *
 * const openrouter = createOpenRouter({
 *   apiKey: process.env.OPENROUTER_API_KEY!,
 * });
 *
 * export const adminRouter = createAdminRouter({
 *   storage,
 *   translator: createAiSdkTranslator({
 *     model: openrouter(process.env.LLM_MODEL!),
 *   }),
 * });
 *
 * // Then merge into your app router
 * export const appRouter = router({
 *   admin: adminRouter,
 * });
 * ```
 */

import type { StorageAdapter } from '@sylphx/rosetta';
import { TRPCError, initTRPC } from '@trpc/server';
import {
	type ZodArray,
	type ZodBoolean,
	type ZodObject,
	type ZodOptional,
	type ZodString,
	z,
} from 'zod';
import type { TranslateFunction } from '../core/types';
import { type AdminServiceConfig, createAdminService } from './service';

// Schema definitions with explicit types for isolatedDeclarations
const SaveTranslationSchema: ZodObject<{
	sourceHash: ZodString;
	locale: ZodString;
	translatedText: ZodString;
	autoGenerated: ZodOptional<ZodBoolean>;
	translatedFrom: ZodOptional<ZodString>;
}> = z.object({
	sourceHash: z.string(),
	locale: z.string(),
	translatedText: z.string(),
	autoGenerated: z.boolean().optional(),
	translatedFrom: z.string().optional(),
});

const MarkAsReviewedSchema: ZodObject<{
	sourceHash: ZodString;
	locale: ZodString;
}> = z.object({
	sourceHash: z.string(),
	locale: z.string(),
});

const BatchTranslateSchema: ZodObject<{
	locale: ZodString;
	hashes: ZodOptional<ZodArray<ZodString>>;
}> = z.object({
	locale: z.string(),
	hashes: z.array(z.string()).optional(),
});

const AddLocaleSchema: ZodObject<{
	locale: ZodString;
}> = z.object({
	locale: z.string(),
});

export interface CreateAdminRouterConfig extends AdminServiceConfig {
	/**
	 * Custom tRPC instance (optional)
	 * If not provided, uses a basic tRPC instance
	 */
	t?: ReturnType<typeof initTRPC.create>;
}

/**
 * Create tRPC router for translation admin
 */
// eslint-disable-next-line @typescript-eslint/explicit-function-return-type
export function createAdminRouter(
	config: CreateAdminRouterConfig
): ReturnType<ReturnType<typeof initTRPC.create>['router']> {
	const { t: customT, ...serviceConfig } = config;

	// Use custom tRPC or create a basic one
	const t = customT ?? initTRPC.create();

	const service = createAdminService(serviceConfig);

	return t.router({
		/**
		 * Fetch all translations, stats, and locales
		 */
		getTranslations: t.procedure.query(async () => {
			return await service.fetchTranslations();
		}),

		/**
		 * Save a single translation
		 */
		saveTranslation: t.procedure.input(SaveTranslationSchema).mutation(async ({ input }) => {
			await service.saveTranslation(input);
			return { success: true };
		}),

		/**
		 * Mark a translation as reviewed
		 */
		markAsReviewed: t.procedure.input(MarkAsReviewedSchema).mutation(async ({ input }) => {
			try {
				await service.markAsReviewed(input);
				return { success: true };
			} catch (err) {
				throw new TRPCError({
					code: 'INTERNAL_SERVER_ERROR',
					message: err instanceof Error ? err.message : 'Failed to mark as reviewed',
				});
			}
		}),

		/**
		 * Batch translate using AI
		 */
		batchTranslate: t.procedure.input(BatchTranslateSchema).mutation(async ({ input }) => {
			try {
				return await service.batchTranslate(input);
			} catch (err) {
				throw new TRPCError({
					code: 'INTERNAL_SERVER_ERROR',
					message: err instanceof Error ? err.message : 'Batch translation failed',
				});
			}
		}),

		/**
		 * Get active locales
		 */
		getLocales: t.procedure.query(async () => {
			return await service.getActiveLocales();
		}),

		/**
		 * Add a new locale (no-op by default, just returns success)
		 * Override in your app if you need to persist locale settings
		 */
		addLocale: t.procedure.input(AddLocaleSchema).mutation(async ({ input }) => {
			// This is a no-op by default
			// The locale will appear once translations are added
			return { success: true, locale: input.locale };
		}),
	});
}

export type AdminRouter = ReturnType<typeof createAdminRouter>;

/**
 * Type helper for inferring router types
 */
export type AdminRouterInput = {
	saveTranslation: z.infer<typeof SaveTranslationSchema>;
	markAsReviewed: z.infer<typeof MarkAsReviewedSchema>;
	batchTranslate: z.infer<typeof BatchTranslateSchema>;
	addLocale: z.infer<typeof AddLocaleSchema>;
};
