/**
 * Core types for rosetta-admin
 * Framework-agnostic, can be used by React, Vue, Solid, etc.
 */

// ============================================
// Translation Status Types
// ============================================

/**
 * Translation status for a specific locale
 */
export type TranslationStatus = 'missing' | 'outdated' | 'unreviewed' | 'reviewed' | 'current';

/**
 * Determine translation status from translation data
 */
export function getTranslationStatus(
	translation: TranslationData | null,
	isOutdated: boolean
): TranslationStatus {
	if (!translation?.text) return 'missing';
	if (isOutdated) return 'outdated';
	if (!translation.reviewed) return 'unreviewed';
	return 'current';
}

// ============================================
// Data Types
// ============================================

/**
 * Translation data for a single locale
 */
export interface TranslationData {
	/** Translated text */
	text: string | null;
	/** Whether this was auto-generated by AI */
	auto: boolean;
	/** Whether this has been reviewed by a human */
	reviewed: boolean;
	/** Source text at time of translation (for staleness detection) */
	translatedFrom?: string | null;
	/** Whether translation is outdated (source changed since translation) */
	outdated: boolean;
}

/**
 * Source string with all its translations
 */
export interface SourceEntry {
	/** Source hash (unique identifier) */
	sourceHash: string;
	/** Original text from code */
	sourceText: string;
	/** Effective source text (override or original) */
	effectiveSource: string;
	/** Optional context for disambiguation */
	context?: string | null;
	/** Translations keyed by locale */
	translations: Record<string, TranslationData | null>;
}

/**
 * Statistics for a single locale
 */
export interface LocaleStats {
	/** Number of translated strings */
	translated: number;
	/** Number of reviewed translations */
	reviewed: number;
	/** Number of outdated translations (source changed) */
	outdated: number;
	/** Total source strings */
	total: number;
}

/**
 * Aggregated translation statistics
 */
export interface TranslationStatsData {
	/** Total number of source strings */
	totalStrings: number;
	/** Stats per locale */
	locales: Record<string, LocaleStats>;
}

// ============================================
// API Response Types
// ============================================

/**
 * Response from GET /translations endpoint
 */
export interface FetchTranslationsResponse {
	sources: SourceEntry[];
	stats: TranslationStatsData;
	locales: string[];
}

/**
 * Request body for saving a translation
 */
export interface SaveTranslationRequest {
	sourceHash: string;
	locale: string;
	translatedText: string;
	autoGenerated?: boolean;
	translatedFrom?: string;
}

/**
 * Request body for marking as reviewed
 */
export interface MarkAsReviewedRequest {
	sourceHash: string;
	locale: string;
}

/**
 * Item for batch translation
 */
export interface BatchTranslationItem {
	sourceHash: string;
	sourceText: string;
	context?: string | null;
}

/**
 * Request body for batch translation
 * Server-first: server finds untranslated strings
 */
export interface BatchTranslateRequest {
	locale: string;
	/** Optional: specific hashes to translate (if omitted, translates all missing) */
	hashes?: string[];
}

/**
 * Response from batch translation
 */
export interface BatchTranslateResponse {
	success: boolean;
	translated: number;
	total: number;
	translations: Array<{
		sourceHash: string;
		translatedText: string;
	}>;
}

// ============================================
// SSE Streaming Types
// ============================================

/**
 * SSE event: Progress update
 */
export interface BatchProgressEvent {
	type: 'progress';
	current: number;
	total: number;
}

/**
 * SSE event: Translation completed for a single item
 */
export interface BatchTranslationEvent {
	type: 'translation';
	sourceHash: string;
	translatedText: string;
}

/**
 * SSE event: Batch completed
 */
export interface BatchCompleteEvent {
	type: 'complete';
	success: boolean;
	translated: number;
	total: number;
}

/**
 * SSE event: Error occurred
 */
export interface BatchErrorEvent {
	type: 'error';
	message: string;
}

/**
 * All SSE event types
 */
export type BatchStreamEvent =
	| BatchProgressEvent
	| BatchTranslationEvent
	| BatchCompleteEvent
	| BatchErrorEvent;

// ============================================
// Store State Types
// ============================================

/**
 * Filter options for translation editor
 */
export type StatusFilter = 'all' | 'missing' | 'outdated' | 'unreviewed' | 'reviewed';

/**
 * View state
 */
export type ViewState = 'dashboard' | 'editor';

/**
 * Progress for a single locale's batch translation
 */
export interface LocaleBatchProgress {
	current: number;
	total: number;
}

/**
 * Admin store state (framework-agnostic)
 */
export interface AdminState {
	// Data
	sources: SourceEntry[];
	locales: string[];
	stats: TranslationStatsData;

	// View state
	view: ViewState;
	activeLocale: string | null;

	// Editor state
	searchQuery: string;
	statusFilter: StatusFilter;
	editingHash: string | null;

	// Loading states
	isLoading: boolean;
	/** Per-locale batch translation progress (null = not translating) */
	batchProgress: Record<string, LocaleBatchProgress | null>;

	// Error state
	error: string | null;
}

/**
 * Initial admin state
 */
export const initialAdminState: AdminState = {
	sources: [],
	locales: [],
	stats: { totalStrings: 0, locales: {} },
	view: 'dashboard',
	activeLocale: null,
	searchQuery: '',
	statusFilter: 'all',
	editingHash: null,
	isLoading: false,
	batchProgress: {},
	error: null,
};

// ============================================
// API Client Interface
// ============================================

/**
 * Translation function for AI batch translation
 */
export interface TranslateFunction {
	(items: BatchTranslationItem[], targetLocale: string): Promise<
		Array<{ sourceHash: string; translatedText: string }>
	>;
}

/**
 * Callback for streaming batch translation events
 */
export interface BatchTranslateStreamCallbacks {
	/** Called on progress updates */
	onProgress?: (current: number, total: number) => void;
	/** Called when a single translation completes */
	onTranslation?: (sourceHash: string, translatedText: string) => void;
	/** Called on error */
	onError?: (message: string) => void;
	/** Called when complete */
	onComplete?: (translated: number, total: number) => void;
}

/**
 * API client interface - implement for REST, tRPC, GraphQL, etc.
 */
export interface AdminAPIClient {
	/** Fetch all sources, stats, and locales */
	fetchTranslations(): Promise<FetchTranslationsResponse>;

	/** Save a single translation */
	saveTranslation(request: SaveTranslationRequest): Promise<void>;

	/** Mark a translation as reviewed */
	markAsReviewed(request: MarkAsReviewedRequest): Promise<void>;

	/** Batch translate using AI (non-streaming) */
	batchTranslate(request: BatchTranslateRequest): Promise<BatchTranslateResponse>;

	/**
	 * Batch translate with streaming progress (optional)
	 * If not implemented, falls back to batchTranslate
	 */
	batchTranslateStream?(
		request: BatchTranslateRequest,
		callbacks: BatchTranslateStreamCallbacks
	): Promise<void>;

	/** Add a new locale */
	addLocale?(locale: string): Promise<void>;

	/** Remove a locale */
	removeLocale?(locale: string): Promise<void>;
}

// ============================================
// Locale Info Types
// ============================================

/**
 * Locale information for display
 */
export interface LocaleInfo {
	/** Locale code (e.g., 'en', 'zh-TW') */
	code: string;
	/** English name (e.g., 'Chinese (Traditional)') */
	name: string;
	/** Native name (e.g., '繁體中文') */
	nativeName: string;
}
