import fs from 'node:fs';
import path from 'node:path';
import type { Rosetta } from '@sylphx/rosetta/server';
import { buildLocaleChain, runWithRosetta } from '@sylphx/rosetta/server';
import type { ReactNode } from 'react';
import { RosettaClientProvider } from './client';

// ============================================
// Auto-sync manifest to storage
// ============================================

const MANIFEST_PATH = path.join(process.cwd(), '.rosetta', 'manifest.json');
let _syncPromise: Promise<void> | null = null;
let _synced = false;

/**
 * Auto-sync extracted strings from manifest to storage
 * - Production: Runs once per server lifecycle
 * - Development: Checks on every request (hot reload support)
 */
async function autoSyncManifest(storage: {
	registerSources: (sources: Array<{ text: string; hash: string }>) => Promise<void>;
}): Promise<void> {
	const isDev = process.env.NODE_ENV !== 'production';

	// In production, only sync once per server lifecycle
	// In development, always check for new manifest (hot reload support)
	if (!isDev && _synced) return;

	// Already syncing (concurrent requests)
	if (_syncPromise) {
		await _syncPromise;
		return;
	}

	// Check if manifest exists
	if (!fs.existsSync(MANIFEST_PATH)) {
		if (!isDev) _synced = true;
		return;
	}

	// Sync manifest to storage
	_syncPromise = (async () => {
		try {
			const manifest = JSON.parse(fs.readFileSync(MANIFEST_PATH, 'utf-8'));
			if (Array.isArray(manifest) && manifest.length > 0) {
				await storage.registerSources(manifest);
				// Delete manifest after successful sync
				fs.unlinkSync(MANIFEST_PATH);
				console.log(`[rosetta] ✓ Auto-synced ${manifest.length} strings to storage`);
			}
		} catch (error) {
			console.error('[rosetta] Auto-sync failed:', error);
		} finally {
			if (!isDev) _synced = true;
			_syncPromise = null;
		}
	})();

	await _syncPromise;
}

// ============================================
// Types
// ============================================

/**
 * Translation manifest mapping routes to required hashes
 * Generated by build plugin for fine-grained loading
 */
export type RosettaManifest = Record<string, string[]>;

export interface RosettaProviderProps {
	/** Rosetta instance */
	rosetta: Rosetta;
	/** Current locale (e.g., from URL params) */
	locale: string;
	/** Children to render */
	children: ReactNode;
	/**
	 * Specific hashes to load (fine-grained loading)
	 * If provided, only these translations are loaded
	 * If not provided, all translations for the locale are loaded
	 */
	hashes?: string[];
}

// ============================================
// Server Provider
// ============================================

/**
 * RosettaProvider - Server component that sets up translation context
 *
 * This is an async server component that:
 * 1. Loads translations for the specified locale
 * 2. Sets up AsyncLocalStorage context for server components
 * 3. Provides React context for client components via RosettaClientProvider
 *
 * @example
 * // Basic usage - loads all translations
 * // app/[locale]/layout.tsx
 * import { RosettaProvider } from '@sylphx/rosetta-next/server';
 * import { rosetta } from '@/lib/i18n';
 *
 * export default async function Layout({ children, params }) {
 *   return (
 *     <RosettaProvider rosetta={rosetta} locale={params.locale}>
 *       <html lang={params.locale}>
 *         <body>{children}</body>
 *       </html>
 *     </RosettaProvider>
 *   );
 * }
 *
 * @example
 * // Fine-grained loading with manifest (faster)
 * import manifest from './rosetta-manifest.json';
 *
 * export default async function Layout({ children, params }) {
 *   const route = '/products'; // or derive from pathname
 *   const hashes = manifest[route]; // ['hash1', 'hash2', ...]
 *
 *   return (
 *     <RosettaProvider rosetta={rosetta} locale={params.locale} hashes={hashes}>
 *       <html lang={params.locale}>
 *         <body>{children}</body>
 *       </html>
 *     </RosettaProvider>
 *   );
 * }
 *
 * @example
 * // In server components - use t() directly
 * import { t } from '@sylphx/rosetta/server';
 * function MyComponent() {
 *   return <h1>{t("Hello World")}</h1>;
 * }
 *
 * @example
 * // In client components - use useT hook
 * 'use client';
 * import { useT } from '@sylphx/rosetta-next';
 * function MyButton() {
 *   const t = useT();
 *   return <button>{t("Click me")}</button>;
 * }
 */
export async function RosettaProvider({
	rosetta,
	locale,
	children,
	hashes,
}: RosettaProviderProps): Promise<React.ReactElement> {
	// Auto-sync manifest to storage on first render (once per server lifecycle)
	await autoSyncManifest(rosetta.getStorage());

	// Load translations - fine-grained if hashes provided, otherwise all
	// Translations are already merged from fallback chain (zh-TW → zh → en)
	const translations = hashes
		? await rosetta.loadTranslationsByHashes(locale, hashes)
		: await rosetta.loadTranslations(locale);
	const defaultLocale = rosetta.getDefaultLocale();
	const localeChain = buildLocaleChain(locale, defaultLocale);

	// Run within AsyncLocalStorage context for server components
	// and provide React context for client components
	return runWithRosetta(
		{
			locale,
			defaultLocale,
			localeChain,
			translations,
			storage: rosetta.getStorage(),
		},
		() => (
			<RosettaClientProvider
				locale={locale}
				defaultLocale={defaultLocale}
				translations={Object.fromEntries(translations)}
			>
				{children}
			</RosettaClientProvider>
		)
	);
}
