import type { ReactNode } from 'react';
import type { Rosetta } from '@sylphx/rosetta/server';
import { runWithRosetta, flushCollectedStrings } from '@sylphx/rosetta/server';
import { RosettaClientProvider } from './client';

// ============================================
// Types
// ============================================

/**
 * Translation manifest mapping routes to required hashes
 * Generated by build plugin for fine-grained loading
 */
export type RosettaManifest = Record<string, string[]>;

export interface RosettaProviderProps {
	/** Rosetta instance */
	rosetta: Rosetta;
	/** Current locale (e.g., from URL params) */
	locale: string;
	/** Children to render */
	children: ReactNode;
	/**
	 * Specific hashes to load (fine-grained loading)
	 * If provided, only these translations are loaded
	 * If not provided, all translations for the locale are loaded
	 */
	hashes?: string[];
}

// ============================================
// Server Provider
// ============================================

/**
 * RosettaProvider - Server component that sets up translation context
 *
 * This is an async server component that:
 * 1. Loads translations for the specified locale
 * 2. Sets up AsyncLocalStorage context for server components
 * 3. Provides React context for client components via RosettaClientProvider
 *
 * @example
 * // Basic usage - loads all translations
 * // app/[locale]/layout.tsx
 * import { RosettaProvider } from '@sylphx/rosetta-next/server';
 * import { rosetta } from '@/lib/i18n';
 *
 * export default async function Layout({ children, params }) {
 *   return (
 *     <RosettaProvider rosetta={rosetta} locale={params.locale}>
 *       <html lang={params.locale}>
 *         <body>{children}</body>
 *       </html>
 *     </RosettaProvider>
 *   );
 * }
 *
 * @example
 * // Fine-grained loading with manifest (faster)
 * import manifest from './rosetta-manifest.json';
 *
 * export default async function Layout({ children, params }) {
 *   const route = '/products'; // or derive from pathname
 *   const hashes = manifest[route]; // ['hash1', 'hash2', ...]
 *
 *   return (
 *     <RosettaProvider rosetta={rosetta} locale={params.locale} hashes={hashes}>
 *       <html lang={params.locale}>
 *         <body>{children}</body>
 *       </html>
 *     </RosettaProvider>
 *   );
 * }
 *
 * @example
 * // In server components - use t() directly
 * import { t } from '@sylphx/rosetta/server';
 * function MyComponent() {
 *   return <h1>{t("Hello World")}</h1>;
 * }
 *
 * @example
 * // In client components - use useT hook
 * 'use client';
 * import { useT } from '@sylphx/rosetta-next';
 * function MyButton() {
 *   const t = useT();
 *   return <button>{t("Click me")}</button>;
 * }
 */
export async function RosettaProvider({
	rosetta,
	locale,
	children,
	hashes,
}: RosettaProviderProps): Promise<React.ReactElement> {
	// Load translations - fine-grained if hashes provided, otherwise all
	const translations = hashes
		? await rosetta.loadTranslationsByHashes(locale, hashes)
		: await rosetta.loadTranslations(locale);
	const defaultLocale = rosetta.getDefaultLocale();

	// Run within AsyncLocalStorage context for server components
	// and provide React context for client components
	return runWithRosetta(
		{
			locale,
			defaultLocale,
			translations,
			storage: rosetta.getStorage(),
		},
		() => {
			// Schedule flush at end of request (non-blocking)
			// Using Promise.resolve().then() to defer without blocking render
			Promise.resolve().then(() => flushCollectedStrings());

			return (
				<RosettaClientProvider
					locale={locale}
					defaultLocale={defaultLocale}
					translations={Object.fromEntries(translations)}
				>
					{children}
				</RosettaClientProvider>
			);
		}
	);
}
