/**
 * Schema helpers for Drizzle ORM
 *
 * These helpers create the necessary tables for @sylphx/rosetta.
 * Import and use in your Drizzle schema file.
 *
 * @example PostgreSQL
 * ```ts
 * // schema.ts
 * import { pgTable, text, timestamp, integer, boolean, unique } from 'drizzle-orm/pg-core';
 * import { createRosettaSchema } from '@sylphx/rosetta-drizzle/schema';
 *
 * export const { rosettaSources, rosettaTranslations } = createRosettaSchema({
 *   pgTable,
 *   text,
 *   timestamp,
 *   integer,
 *   boolean,
 *   unique,
 * });
 * ```
 *
 * @example SQLite
 * ```ts
 * // schema.ts
 * import { sqliteTable, text, integer } from 'drizzle-orm/sqlite-core';
 * import { createRosettaSchemaSQLite } from '@sylphx/rosetta-drizzle/schema';
 *
 * export const { rosettaSources, rosettaTranslations } = createRosettaSchemaSQLite({
 *   sqliteTable,
 *   text,
 *   integer,
 * });
 * ```
 */

// ============================================
// PostgreSQL Schema
// ============================================

export interface PostgresSchemaHelpers {
	pgTable: typeof import('drizzle-orm/pg-core').pgTable;
	text: typeof import('drizzle-orm/pg-core').text;
	timestamp: typeof import('drizzle-orm/pg-core').timestamp;
	integer: typeof import('drizzle-orm/pg-core').integer;
	boolean: typeof import('drizzle-orm/pg-core').boolean;
	unique: typeof import('drizzle-orm/pg-core').unique;
	serial?: typeof import('drizzle-orm/pg-core').serial;
}

export interface RosettaSchemaOptions {
	/**
	 * Custom table name for sources (default: 'rosetta_sources')
	 */
	sourcesTable?: string;
	/**
	 * Custom table name for translations (default: 'rosetta_translations')
	 */
	translationsTable?: string;
}

/**
 * Create Rosetta schema for PostgreSQL
 */
export function createRosettaSchema<T extends PostgresSchemaHelpers>(
	helpers: T,
	options: RosettaSchemaOptions = {}
): { rosettaSources: object; rosettaTranslations: object } {
	const { pgTable, text, timestamp, integer, boolean, unique, serial } = helpers;
	const sourcesTableName = options.sourcesTable ?? 'rosetta_sources';
	const translationsTableName = options.translationsTable ?? 'rosetta_translations';

	const rosettaSources = pgTable(sourcesTableName, {
		id: serial ? serial('id').primaryKey() : integer('id').primaryKey().generatedAlwaysAsIdentity(),
		hash: text('hash').notNull().unique(),
		text: text('text').notNull(),
		context: text('context'),
		occurrences: integer('occurrences').default(1).notNull(),
		firstSeenAt: timestamp('first_seen_at', { withTimezone: true }).defaultNow().notNull(),
		lastSeenAt: timestamp('last_seen_at', { withTimezone: true }).defaultNow().notNull(),
	});

	const rosettaTranslations = pgTable(
		translationsTableName,
		{
			id: serial
				? serial('id').primaryKey()
				: integer('id').primaryKey().generatedAlwaysAsIdentity(),
			locale: text('locale').notNull(),
			hash: text('hash').notNull(),
			text: text('text').notNull(),
			autoGenerated: boolean('auto_generated').default(false).notNull(),
			reviewed: boolean('reviewed').default(false).notNull(),
			createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
			updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
		},
		(table) => [unique().on(table.locale, table.hash)]
	);

	const result = { rosettaSources: rosettaSources, rosettaTranslations: rosettaTranslations };
	return result;
}

// ============================================
// SQLite Schema
// ============================================

export interface SQLiteSchemaHelpers {
	sqliteTable: typeof import('drizzle-orm/sqlite-core').sqliteTable;
	text: typeof import('drizzle-orm/sqlite-core').text;
	integer: typeof import('drizzle-orm/sqlite-core').integer;
	unique?: typeof import('drizzle-orm/sqlite-core').unique;
}

/**
 * Create Rosetta schema for SQLite
 */
export function createRosettaSchemaSQLite<T extends SQLiteSchemaHelpers>(
	helpers: T,
	options: RosettaSchemaOptions = {}
): { rosettaSources: object; rosettaTranslations: object } {
	const { sqliteTable, text, integer, unique } = helpers;
	const sourcesTableName = options.sourcesTable ?? 'rosetta_sources';
	const translationsTableName = options.translationsTable ?? 'rosetta_translations';

	const rosettaSources = sqliteTable(sourcesTableName, {
		id: integer('id').primaryKey({ autoIncrement: true }),
		hash: text('hash').notNull().unique(),
		text: text('text').notNull(),
		context: text('context'),
		occurrences: integer('occurrences').default(1).notNull(),
		firstSeenAt: integer('first_seen_at', { mode: 'timestamp' })
			.$defaultFn(() => new Date())
			.notNull(),
		lastSeenAt: integer('last_seen_at', { mode: 'timestamp' })
			.$defaultFn(() => new Date())
			.notNull(),
	});

	const rosettaTranslations = sqliteTable(
		translationsTableName,
		{
			id: integer('id').primaryKey({ autoIncrement: true }),
			locale: text('locale').notNull(),
			hash: text('hash').notNull(),
			text: text('text').notNull(),
			autoGenerated: integer('auto_generated', { mode: 'boolean' }).default(false).notNull(),
			reviewed: integer('reviewed', { mode: 'boolean' }).default(false).notNull(),
			createdAt: integer('created_at', { mode: 'timestamp' })
				.$defaultFn(() => new Date())
				.notNull(),
			updatedAt: integer('updated_at', { mode: 'timestamp' })
				.$defaultFn(() => new Date())
				.notNull(),
		},
		(table) => (unique ? [unique().on(table.locale, table.hash)] : [])
	);

	const result = { rosettaSources: rosettaSources, rosettaTranslations: rosettaTranslations };
	return result;
}

// ============================================
// MySQL Schema
// ============================================

export interface MySQLSchemaHelpers {
	mysqlTable: typeof import('drizzle-orm/mysql-core').mysqlTable;
	text: typeof import('drizzle-orm/mysql-core').text;
	varchar: typeof import('drizzle-orm/mysql-core').varchar;
	timestamp: typeof import('drizzle-orm/mysql-core').timestamp;
	int: typeof import('drizzle-orm/mysql-core').int;
	boolean: typeof import('drizzle-orm/mysql-core').boolean;
	unique?: typeof import('drizzle-orm/mysql-core').unique;
	serial?: typeof import('drizzle-orm/mysql-core').serial;
}

/**
 * Create Rosetta schema for MySQL
 */
export function createRosettaSchemaMySQL<T extends MySQLSchemaHelpers>(
	helpers: T,
	options: RosettaSchemaOptions = {}
): { rosettaSources: object; rosettaTranslations: object } {
	const { mysqlTable, text, varchar, timestamp, int, boolean, unique, serial } = helpers;
	const sourcesTableName = options.sourcesTable ?? 'rosetta_sources';
	const translationsTableName = options.translationsTable ?? 'rosetta_translations';

	const rosettaSources = mysqlTable(sourcesTableName, {
		id: serial ? serial('id').primaryKey() : int('id').primaryKey().autoincrement(),
		hash: varchar('hash', { length: 32 }).notNull().unique(),
		text: text('text').notNull(),
		context: varchar('context', { length: 255 }),
		occurrences: int('occurrences').default(1).notNull(),
		firstSeenAt: timestamp('first_seen_at').defaultNow().notNull(),
		lastSeenAt: timestamp('last_seen_at').defaultNow().notNull(),
	});

	const rosettaTranslations = mysqlTable(
		translationsTableName,
		{
			id: serial ? serial('id').primaryKey() : int('id').primaryKey().autoincrement(),
			locale: varchar('locale', { length: 10 }).notNull(),
			hash: varchar('hash', { length: 32 }).notNull(),
			text: text('text').notNull(),
			autoGenerated: boolean('auto_generated').default(false).notNull(),
			reviewed: boolean('reviewed').default(false).notNull(),
			createdAt: timestamp('created_at').defaultNow().notNull(),
			updatedAt: timestamp('updated_at').defaultNow().notNull(),
		},
		(table) => (unique ? [unique().on(table.locale, table.hash)] : [])
	);

	const result = { rosettaSources: rosettaSources, rosettaTranslations: rosettaTranslations };
	return result;
}

// ============================================
// Type Inference Helpers
// ============================================

/**
 * Infer the type of a Rosetta sources table
 */
export type RosettaSourcesTable = ReturnType<typeof createRosettaSchema>['rosettaSources'];

/**
 * Infer the type of a Rosetta translations table
 */
export type RosettaTranslationsTable = ReturnType<typeof createRosettaSchema>['rosettaTranslations'];
