/**
 * Schema helpers for Drizzle ORM
 *
 * Pre-built schemas for @sylphx/rosetta. Just import and spread into your schema.
 *
 * @example PostgreSQL
 * ```ts
 * import { createRosettaSchema } from '@sylphx/rosetta-drizzle';
 *
 * export const { rosettaSources, rosettaTranslations } = createRosettaSchema();
 * ```
 *
 * @example SQLite
 * ```ts
 * import { createRosettaSchemaSQLite } from '@sylphx/rosetta-drizzle';
 *
 * export const { rosettaSources, rosettaTranslations } = createRosettaSchemaSQLite();
 * ```
 *
 * @example MySQL
 * ```ts
 * import { createRosettaSchemaMySQL } from '@sylphx/rosetta-drizzle';
 *
 * export const { rosettaSources, rosettaTranslations } = createRosettaSchemaMySQL();
 * ```
 */

import {
	boolean as pgBoolean,
	integer as pgInteger,
	pgTable,
	text as pgText,
	timestamp as pgTimestamp,
	unique as pgUnique,
} from 'drizzle-orm/pg-core';

import {
	integer as sqliteInteger,
	sqliteTable,
	text as sqliteText,
	unique as sqliteUnique,
} from 'drizzle-orm/sqlite-core';

import {
	boolean as mysqlBoolean,
	int as mysqlInt,
	mysqlTable,
	text as mysqlText,
	timestamp as mysqlTimestamp,
	unique as mysqlUnique,
	varchar as mysqlVarchar,
} from 'drizzle-orm/mysql-core';

// ============================================
// Options
// ============================================

export interface RosettaSchemaOptions {
	/**
	 * Custom table name for sources (default: 'rosetta_sources')
	 */
	sourcesTable?: string;
	/**
	 * Custom table name for translations (default: 'rosetta_translations')
	 */
	translationsTable?: string;
}

// ============================================
// PostgreSQL Tables
// ============================================

export const pgRosettaSources = pgTable('rosetta_sources', {
	id: pgInteger('id').primaryKey().generatedAlwaysAsIdentity(),
	hash: pgText('hash').notNull().unique(),
	text: pgText('text').notNull(),
	context: pgText('context'),
	occurrences: pgInteger('occurrences').default(1).notNull(),
	firstSeenAt: pgTimestamp('first_seen_at', { withTimezone: true }).defaultNow().notNull(),
	lastSeenAt: pgTimestamp('last_seen_at', { withTimezone: true }).defaultNow().notNull(),
});

export const pgRosettaTranslations = pgTable(
	'rosetta_translations',
	{
		id: pgInteger('id').primaryKey().generatedAlwaysAsIdentity(),
		locale: pgText('locale').notNull(),
		hash: pgText('hash').notNull(),
		text: pgText('text').notNull(),
		autoGenerated: pgBoolean('auto_generated').default(false).notNull(),
		reviewed: pgBoolean('reviewed').default(false).notNull(),
		createdAt: pgTimestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
		updatedAt: pgTimestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
	},
	(table) => [pgUnique().on(table.locale, table.hash)]
);

/** PostgreSQL schema */
export const pgRosettaSchema = {
	rosettaSources: pgRosettaSources,
	rosettaTranslations: pgRosettaTranslations,
} as const;

/** PostgreSQL schema type */
export type PgRosettaSchema = typeof pgRosettaSchema;

/**
 * Create Rosetta schema for PostgreSQL with optional custom table names
 *
 * @example Default table names
 * ```ts
 * const { rosettaSources, rosettaTranslations } = createRosettaSchema();
 * // Tables: rosetta_sources, rosetta_translations
 * ```
 *
 * @example Custom table names
 * ```ts
 * const { rosettaSources, rosettaTranslations } = createRosettaSchema({
 *   sourcesTable: 'i18n_sources',
 *   translationsTable: 'i18n_translations',
 * });
 * ```
 */
export function createRosettaSchema(options?: RosettaSchemaOptions) {
	const sourcesTableName = options?.sourcesTable ?? 'rosetta_sources';
	const translationsTableName = options?.translationsTable ?? 'rosetta_translations';

	// Return default static schema if using default names (better type inference)
	if (sourcesTableName === 'rosetta_sources' && translationsTableName === 'rosetta_translations') {
		return pgRosettaSchema;
	}

	// Create dynamic schema with custom names
	const rosettaSources = pgTable(sourcesTableName, {
		id: pgInteger('id').primaryKey().generatedAlwaysAsIdentity(),
		hash: pgText('hash').notNull().unique(),
		text: pgText('text').notNull(),
		context: pgText('context'),
		occurrences: pgInteger('occurrences').default(1).notNull(),
		firstSeenAt: pgTimestamp('first_seen_at', { withTimezone: true }).defaultNow().notNull(),
		lastSeenAt: pgTimestamp('last_seen_at', { withTimezone: true }).defaultNow().notNull(),
	});

	const rosettaTranslations = pgTable(
		translationsTableName,
		{
			id: pgInteger('id').primaryKey().generatedAlwaysAsIdentity(),
			locale: pgText('locale').notNull(),
			hash: pgText('hash').notNull(),
			text: pgText('text').notNull(),
			autoGenerated: pgBoolean('auto_generated').default(false).notNull(),
			reviewed: pgBoolean('reviewed').default(false).notNull(),
			createdAt: pgTimestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
			updatedAt: pgTimestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
		},
		(table) => [pgUnique().on(table.locale, table.hash)]
	);

	return { rosettaSources, rosettaTranslations };
}

// ============================================
// SQLite Tables
// ============================================

export const sqliteRosettaSources = sqliteTable('rosetta_sources', {
	id: sqliteInteger('id').primaryKey({ autoIncrement: true }),
	hash: sqliteText('hash').notNull().unique(),
	text: sqliteText('text').notNull(),
	context: sqliteText('context'),
	occurrences: sqliteInteger('occurrences').default(1).notNull(),
	firstSeenAt: sqliteInteger('first_seen_at', { mode: 'timestamp' })
		.$defaultFn(() => new Date())
		.notNull(),
	lastSeenAt: sqliteInteger('last_seen_at', { mode: 'timestamp' })
		.$defaultFn(() => new Date())
		.notNull(),
});

export const sqliteRosettaTranslations = sqliteTable(
	'rosetta_translations',
	{
		id: sqliteInteger('id').primaryKey({ autoIncrement: true }),
		locale: sqliteText('locale').notNull(),
		hash: sqliteText('hash').notNull(),
		text: sqliteText('text').notNull(),
		autoGenerated: sqliteInteger('auto_generated', { mode: 'boolean' }).default(false).notNull(),
		reviewed: sqliteInteger('reviewed', { mode: 'boolean' }).default(false).notNull(),
		createdAt: sqliteInteger('created_at', { mode: 'timestamp' })
			.$defaultFn(() => new Date())
			.notNull(),
		updatedAt: sqliteInteger('updated_at', { mode: 'timestamp' })
			.$defaultFn(() => new Date())
			.notNull(),
	},
	(table) => [sqliteUnique().on(table.locale, table.hash)]
);

/** SQLite schema */
export const sqliteRosettaSchema = {
	rosettaSources: sqliteRosettaSources,
	rosettaTranslations: sqliteRosettaTranslations,
} as const;

/** SQLite schema type */
export type SqliteRosettaSchema = typeof sqliteRosettaSchema;

/**
 * Create Rosetta schema for SQLite with optional custom table names
 *
 * @example Default table names
 * ```ts
 * const { rosettaSources, rosettaTranslations } = createRosettaSchemaSQLite();
 * // Tables: rosetta_sources, rosetta_translations
 * ```
 *
 * @example Custom table names
 * ```ts
 * const { rosettaSources, rosettaTranslations } = createRosettaSchemaSQLite({
 *   sourcesTable: 'i18n_sources',
 *   translationsTable: 'i18n_translations',
 * });
 * ```
 */
export function createRosettaSchemaSQLite(options?: RosettaSchemaOptions) {
	const sourcesTableName = options?.sourcesTable ?? 'rosetta_sources';
	const translationsTableName = options?.translationsTable ?? 'rosetta_translations';

	// Return default static schema if using default names (better type inference)
	if (sourcesTableName === 'rosetta_sources' && translationsTableName === 'rosetta_translations') {
		return sqliteRosettaSchema;
	}

	// Create dynamic schema with custom names
	const rosettaSources = sqliteTable(sourcesTableName, {
		id: sqliteInteger('id').primaryKey({ autoIncrement: true }),
		hash: sqliteText('hash').notNull().unique(),
		text: sqliteText('text').notNull(),
		context: sqliteText('context'),
		occurrences: sqliteInteger('occurrences').default(1).notNull(),
		firstSeenAt: sqliteInteger('first_seen_at', { mode: 'timestamp' })
			.$defaultFn(() => new Date())
			.notNull(),
		lastSeenAt: sqliteInteger('last_seen_at', { mode: 'timestamp' })
			.$defaultFn(() => new Date())
			.notNull(),
	});

	const rosettaTranslations = sqliteTable(
		translationsTableName,
		{
			id: sqliteInteger('id').primaryKey({ autoIncrement: true }),
			locale: sqliteText('locale').notNull(),
			hash: sqliteText('hash').notNull(),
			text: sqliteText('text').notNull(),
			autoGenerated: sqliteInteger('auto_generated', { mode: 'boolean' }).default(false).notNull(),
			reviewed: sqliteInteger('reviewed', { mode: 'boolean' }).default(false).notNull(),
			createdAt: sqliteInteger('created_at', { mode: 'timestamp' })
				.$defaultFn(() => new Date())
				.notNull(),
			updatedAt: sqliteInteger('updated_at', { mode: 'timestamp' })
				.$defaultFn(() => new Date())
				.notNull(),
		},
		(table) => [sqliteUnique().on(table.locale, table.hash)]
	);

	return { rosettaSources, rosettaTranslations };
}

// ============================================
// MySQL Tables
// ============================================

export const mysqlRosettaSources = mysqlTable('rosetta_sources', {
	id: mysqlInt('id').primaryKey().autoincrement(),
	hash: mysqlVarchar('hash', { length: 32 }).notNull().unique(),
	text: mysqlText('text').notNull(),
	context: mysqlVarchar('context', { length: 255 }),
	occurrences: mysqlInt('occurrences').default(1).notNull(),
	firstSeenAt: mysqlTimestamp('first_seen_at').defaultNow().notNull(),
	lastSeenAt: mysqlTimestamp('last_seen_at').defaultNow().notNull(),
});

export const mysqlRosettaTranslations = mysqlTable(
	'rosetta_translations',
	{
		id: mysqlInt('id').primaryKey().autoincrement(),
		locale: mysqlVarchar('locale', { length: 10 }).notNull(),
		hash: mysqlVarchar('hash', { length: 32 }).notNull(),
		text: mysqlText('text').notNull(),
		autoGenerated: mysqlBoolean('auto_generated').default(false).notNull(),
		reviewed: mysqlBoolean('reviewed').default(false).notNull(),
		createdAt: mysqlTimestamp('created_at').defaultNow().notNull(),
		updatedAt: mysqlTimestamp('updated_at').defaultNow().notNull(),
	},
	(table) => [mysqlUnique().on(table.locale, table.hash)]
);

/** MySQL schema */
export const mysqlRosettaSchema = {
	rosettaSources: mysqlRosettaSources,
	rosettaTranslations: mysqlRosettaTranslations,
} as const;

/** MySQL schema type */
export type MysqlRosettaSchema = typeof mysqlRosettaSchema;

/**
 * Create Rosetta schema for MySQL with optional custom table names
 *
 * @example Default table names
 * ```ts
 * const { rosettaSources, rosettaTranslations } = createRosettaSchemaMySQL();
 * // Tables: rosetta_sources, rosetta_translations
 * ```
 *
 * @example Custom table names
 * ```ts
 * const { rosettaSources, rosettaTranslations } = createRosettaSchemaMySQL({
 *   sourcesTable: 'i18n_sources',
 *   translationsTable: 'i18n_translations',
 * });
 * ```
 */
export function createRosettaSchemaMySQL(options?: RosettaSchemaOptions) {
	const sourcesTableName = options?.sourcesTable ?? 'rosetta_sources';
	const translationsTableName = options?.translationsTable ?? 'rosetta_translations';

	// Return default static schema if using default names (better type inference)
	if (sourcesTableName === 'rosetta_sources' && translationsTableName === 'rosetta_translations') {
		return mysqlRosettaSchema;
	}

	// Create dynamic schema with custom names
	const rosettaSources = mysqlTable(sourcesTableName, {
		id: mysqlInt('id').primaryKey().autoincrement(),
		hash: mysqlVarchar('hash', { length: 32 }).notNull().unique(),
		text: mysqlText('text').notNull(),
		context: mysqlVarchar('context', { length: 255 }),
		occurrences: mysqlInt('occurrences').default(1).notNull(),
		firstSeenAt: mysqlTimestamp('first_seen_at').defaultNow().notNull(),
		lastSeenAt: mysqlTimestamp('last_seen_at').defaultNow().notNull(),
	});

	const rosettaTranslations = mysqlTable(
		translationsTableName,
		{
			id: mysqlInt('id').primaryKey().autoincrement(),
			locale: mysqlVarchar('locale', { length: 10 }).notNull(),
			hash: mysqlVarchar('hash', { length: 32 }).notNull(),
			text: mysqlText('text').notNull(),
			autoGenerated: mysqlBoolean('auto_generated').default(false).notNull(),
			reviewed: mysqlBoolean('reviewed').default(false).notNull(),
			createdAt: mysqlTimestamp('created_at').defaultNow().notNull(),
			updatedAt: mysqlTimestamp('updated_at').defaultNow().notNull(),
		},
		(table) => [mysqlUnique().on(table.locale, table.hash)]
	);

	return { rosettaSources, rosettaTranslations };
}

// ============================================
// Type exports for convenience
// ============================================

/** Type helper to extract table type from createRosettaSchema result */
export type RosettaSourcesTable = typeof pgRosettaSources;
export type RosettaTranslationsTable = typeof pgRosettaTranslations;
